"""Deterministic post-validation command normalization for operator-ready output.

The LLM proposes the command and the reasoning validators verify intent/target.
This module then applies only mechanically safe additions that should not be left
for a small model to remember: required sudo for privileged Nmap modes and a
persistent output artifact for scans.  It never changes the requested target.
"""

from __future__ import annotations

import re
import shlex
from dataclasses import asdict, dataclass

from .command_policy import assess_command_policy, effective_tool


_FENCE_RE = re.compile(r"```(?P<label>[A-Za-z0-9_+.-]*)[ \t]*(?P<body>.*?)```", re.DOTALL)


@dataclass(frozen=True)
class OperationalMutation:
    original_sha256: str
    approved_sha256: str
    sudo_added: bool
    artifact_added: bool
    artifact_path: str | None

    def to_safe_dict(self) -> dict:
        return asdict(self)


def _prepend_sudo(command: str) -> str:
    stripped = command.strip()
    if stripped.casefold().startswith("sudo "):
        return stripped
    return f"sudo {stripped}"


def _append_artifact(command: str, artifact: str) -> str:
    # artifact names are generated by command_policy from a strict slug, but
    # shlex.quote keeps this helper safe if that implementation changes later.
    return f"{command.rstrip()} -oN {shlex.quote(artifact)}"


def normalize_operator_command(message: str, command: str) -> tuple[str, OperationalMutation | None]:
    """Apply deterministic, additive policy to one already-target-verified command."""
    assessment = assess_command_policy(message, command)
    if assessment.effective_tool != "nmap" or not assessment.target_verified:
        return command, None

    approved = command.strip()
    sudo_added = False
    artifact_added = False
    artifact_path = assessment.artifact_path

    if assessment.requires_elevation and not assessment.has_sudo:
        approved = _prepend_sudo(approved)
        sudo_added = True

    # Re-assess after sudo normalization; sudo must not change effective tool.
    after_sudo = assess_command_policy(message, approved)
    if after_sudo.artifact_required and not after_sudo.artifact_present:
        artifact = after_sudo.recommended_artifact
        if artifact:
            approved = _append_artifact(approved, artifact)
            artifact_added = True
            artifact_path = artifact

    if approved == command.strip():
        return command, None

    final = assess_command_policy(message, approved)
    mutation = OperationalMutation(
        original_sha256=assessment.sha256,
        approved_sha256=final.sha256,
        sudo_added=sudo_added,
        artifact_added=artifact_added,
        artifact_path=artifact_path,
    )
    return approved, mutation


def transform_response_commands(message: str, response: str) -> tuple[str, list[OperationalMutation]]:
    """Normalize executable commands inside Markdown fences without touching prose."""
    mutations: list[OperationalMutation] = []

    def replace_fence(match: re.Match[str]) -> str:
        label = match.group("label")
        body = match.group("body")
        output_lines: list[str] = []

        for raw_line in body.splitlines():
            leading = raw_line[: len(raw_line) - len(raw_line.lstrip())]
            candidate = raw_line.strip()
            prompt = ""
            if candidate.startswith("$ "):
                prompt, candidate = "$ ", candidate[2:].lstrip()
            elif candidate.startswith("PS> "):
                prompt, candidate = "PS> ", candidate[4:].lstrip()

            if candidate and effective_tool(candidate):
                approved, mutation = normalize_operator_command(message, candidate)
                if mutation:
                    mutations.append(mutation)
                    candidate = approved
                output_lines.append(f"{leading}{prompt}{candidate}")
            else:
                output_lines.append(raw_line)

        # Preserve standard fenced-block formatting.  Most Luna responses use a
        # newline after the label; normalizing that here also keeps hashing exact.
        transformed_body = "\n".join(output_lines)
        return f"```{label}\n{transformed_body}\n```"

    transformed = _FENCE_RE.sub(replace_fence, response)
    return transformed, mutations
